export const DEFAULT_TIKTOK_PIXEL_ID = "D862IU3C77U8MI6UL9D0";

export const TIKTOK_PIXEL_ID =
  process.env.NEXT_PUBLIC_TIKTOK_PIXEL_ID || DEFAULT_TIKTOK_PIXEL_ID;

export const TIKTOK_CONTACT_EVENT = "Contact";
